name: cicd-utils
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
jobs:
  test_verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: verify test
        run: make test-verify
  test_unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: unit test
        run: make test-unit
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2.2.1
        with:
          version: v1.29
          args: -v -E gofmt --timeout 1h0m0s
  deploy-master:
    if: github.ref == 'refs/heads/master'
    needs: [test_verify, test_unit, test_lint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: shivanshs9/setup-k8s-operator-sdk@v1
      - name: build and push
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}
          make build image push VERSION=master
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test_verify, test_unit, test_lint]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: shivanshs9/setup-k8s-operator-sdk@v1
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}
          make build image tag-latest push push-latest VERSION=${GITHUB_REF#refs/tags/}
